// import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "./ui/navigation/Navigation";
import SignoutBtn from "./ui/signoutBtn/SignoutBtn";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      //  className={inter.className}
      >
        <Navigation />
        <SignoutBtn />
        {children}
      </body>
    </html>
  );
}
